sudo: false
language: python
script: python -m unittest discover -s test
notifications:
  webhooks:
    urls:
      - http://doorbell-nudger.herokuapp.com/travis
    on_pull_requests: false
    on_failure: never
